import { useSession } from 'next-auth/react'
import Head from 'next/head'

export default function ChatRoom() {
//   const {data: session} = useSession()
//   if(!session) return <Login />

  return (
    <div>
      <Head>
        <title>Chirper</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <main className=''>
        chatroom
      </main>
    </div>
  )
}
