import Head from 'next/head'

export default function ChatRoom() {

  return (
    <div>
      <Head>
        <title>Chirper</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <main className=''>
        chatroom
      </main>
    </div>
  )
}
