import Head from 'next/head'
import Feed from '../components/Chirps/Feed'
import { AppContext } from '@/contexts/AppContext'
import React, { useContext, useEffect } from 'react'
import Sidebar from '@/components/Common/Sidebar'
import Trending from '@/components/Common/Trending'

import { useRouter } from 'next/router'

// Component for the home page
export default function Home () {
  const router = useRouter()
  const [appContext] = useContext(AppContext)

  // Set mount flag to true after component has mounted
  const [hasMounted, setHasMounted] = React.useState(false)
  React.useEffect(() => {
    setHasMounted(true)
  }, [])

  // If component has not yet mounted, return null
  if (!hasMounted) {
    return null
  }

  // If user is not logged in, redirect to login page
  if (hasMounted && localStorage.getItem('userId') == null) {
    router.push('/login')
  }

  // Return the main content of the home page
  return (
    <div>
      <Head>
        <title>Chirper - Feed</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div className=" bg-white dark:bg-black">
        <main className='relative max-w-[1400px] mx-auto bg-white dark:bg-black'>
          <Sidebar/>
          <div className='flex gap-6'>
            <div className='sm:ml-20 xl:ml-[340px] w-[600px] min-h-screen border-r border-gray-400 text-white py-2'>
              <Feed />
            </div>
            <Trending />
          </div>
        </main>
      </div>
    </div>
  )
}
