import { useSession } from 'next-auth/react'
import Head from 'next/head'

import Login from '../components/Login'
import Sidebar from '../components/Sidebar'

export default function Home() {
  const {data: session} = useSession()
  if(!session) return <Login />

  return (
    <div>
      <Head>
        <title>Chirper</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <main className='relative max-w-[1400px] mx-auto'>
        <Sidebar /> 
      </main>
    </div>
  )
}
