import React, { useContext } from 'react'
import { getSession, useSession } from 'next-auth/react'
import Login from '@/components/Login'
import Sidebar from '@/components/Common/Sidebar'
import Head from 'next/head'
import SinglePost from '@/components/Chirps/SinglePost'
import { AppContext } from '@/contexts/AppContext'

const PostPage = () => {

  const { data: session } = useSession()
  const [appContext] = useContext(AppContext)

  if (!session) return <Login />

  return (
    <div>
      <Head>
        <title>Chirper - Post</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

          <SinglePost />

    </div>
  )
}

export default PostPage

export async function getServerSideProps(context) {
  const session = await getSession(context);

  return {
    props: {
      session
    },
  };
}