import { signIn } from 'next-auth/react'
import React from 'react'
import Head from 'next/head'
import { BsTwitter } from 'react-icons/bs'
import { FcGoogle } from 'react-icons/fc'

const Login = () => {
  return (
    <>
    <Head>
      <title>Chirper - Login</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
    </Head>
    <div className='grid grid-col-2'>
      <div className='bg-[#1d9bf0] h-screen grid place-items-center relative'>
        <BsTwitter className='text-white text-[200px]'/>
      </div>

      <div className='absolute bottom-20 mx-auto left-0 right-0 w-64 lg:w-80'>
        <div
          className='flex gap-4 bg-white py-4 px-6 items-center rounded-lg cursor-pointer'
          onClick={() => signIn('google')}
        >
          <FcGoogle className='text-4xl'/>
          Sign In with Google
        </div>
      </div>
    </div>
    </>
  )
}

export default Login
