import { signIn } from 'next-auth/react'
import React from 'react'
import Head from 'next/head'
import { BsTwitter } from 'react-icons/bs'
import { FcGoogle } from 'react-icons/fc'

const Login = () => {
  return (
    <>
    <Head>
      <title>Chirper - Login</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
    </Head>
    <div className='grid grid-col-2'>
      <div className='login_background'>
        <BsTwitter className='text-white text-[200px]'/>
      </div>

      <div className='google_sign_in_button'>
        <div
          className='login_button_text'
          onClick={() => signIn('google')}
        >
          <FcGoogle className='login_button_icon'/>
          Sign In with Google
        </div>
      </div>
    </div>
    </>
  )
}

export default Login
