import React from 'react' // Import React library
import Head from 'next/head' // Import Head component from next/head package
import { GiEgyptianBird } from 'react-icons/gi' // Import GiEgyptianBird icon from react-icons/gi package
import { AiOutlineMail } from 'react-icons/ai' // Import AiOutlineMail icon from react-icons/ai package
import { useRouter } from 'next/router' // Import useRouter hook from next/router package

// Define a React component called Login
const Login = () => {
  const router = useRouter() // Initialize a router object using the useRouter hook

  // Define a function called emailSignin that navigates to the login page
  const emailSignin = () => {
    router.push('/login')
  }

  // Use the useState and useEffect hooks to manage the component's state and lifecycle
  const [hasMounted, setHasMounted] = React.useState(false)
  React.useEffect(() => {
    setHasMounted(true)
  }, [])
  
  // If the component has not yet mounted, return null
  if (!hasMounted) {
    return null
  }

  // Return a JSX template that defines the login page's layout
  return (
    <>
      <Head>
        <title>Chirper - Login</title> {/* Set the page title */}
        <meta name="description" content="Generated by create next app" /> {/* Set a meta tag for search engine optimization */}
        <meta name="viewport" content="width=device-width, initial-scale=1" /> {/* Set a meta tag for responsive design */}
      </Head>
      <div className='grid grid-col-2'> {/* Define a grid layout with two columns */}
        <div className='login_background'> {/* Display a background image for the left column */}
          <GiEgyptianBird className='text-white text-[200px]'/> {/* Display the GiEgyptianBird icon */}
        </div>
        <div className='absolute bottom-20 flex left-0 right-0 mx-auto'> {/* Position the buttons at the bottom of the page and center them horizontally */}
          {/* Define a button for signing in with Google */}
          {/* <div className='google_sign_in_button' onClick={() => googleSignin()}>
            <div
              className='login_button_text'
            >
              <FcGoogle className='login_button_icon'/>
              Sign In with Google
            </div>
          </div> */}
          
          {/* Define a button for logging in with email and password */}
          <div className='email_sign_in_button' onClick={() => emailSignin()}>
            <div
              className='login_button_text'
            >
              <AiOutlineMail className='login_button_icon'/>
              Login with Email and Password
            </div>
          </div>

          {/* Define a button for signing up with email and password */}
          <div className='email_sign_in_button' onClick={() => router.push('/signup')}>
            <div
              className='login_button_text'
            >
              <AiOutlineMail className='login_button_icon'/>
              Sign Up with Email and Password
            </div>
          </div>
        </div>
      </div>
    </>
  )
}

export default Login // Export the Login component as the default export
